version: '2'
services:
    # postgresql database
    todolist-postgresql-db:
        extends:
            file: postgresql.yml
            service: todolist-postgresql-db

    # mongodb database
    todolist-mongodb-db:
        extends:
            file: mongodb.yml
            service: todolist-mongodb-db
